{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "9.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.1.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.1.1.jar",
          "url": "gradle-api-9.1.1.jar",
          "size": 389201,
          "sha512": "76f13c4d46798dc7155ffae28d7d08ee0cced258c90e232f5e71886c2f0920e2c6da1b80a80656458a49360b790b249f6e35fb1e0c4e99b86bd7019b25fc5bbc",
          "sha256": "780020a00766ffb09d47f597773f5679d6cc5eebe2650b9ea14045a7e4441b91",
          "sha1": "f8498feda114ca0f77d8cab04d2004d2d5d0f1f3",
          "md5": "e29278b29e178a586e03167dea0090fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.1.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "9.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.1.1.jar",
          "url": "gradle-api-9.1.1.jar",
          "size": 389201,
          "sha512": "76f13c4d46798dc7155ffae28d7d08ee0cced258c90e232f5e71886c2f0920e2c6da1b80a80656458a49360b790b249f6e35fb1e0c4e99b86bd7019b25fc5bbc",
          "sha256": "780020a00766ffb09d47f597773f5679d6cc5eebe2650b9ea14045a7e4441b91",
          "sha1": "f8498feda114ca0f77d8cab04d2004d2d5d0f1f3",
          "md5": "e29278b29e178a586e03167dea0090fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.1.1-javadoc.jar",
          "url": "gradle-api-9.1.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.1.1-sources.jar",
          "url": "gradle-api-9.1.1-sources.jar",
          "size": 372049,
          "sha512": "f17074173c2ec0e3622b8f6e3c0186b3c9a963e59528bf2e9cdc9ec76388f379b8a7d487809b9fe14f33660a3d5cdbc75b2db2efaf3b1c72641619b4e65ec2b1",
          "sha256": "7d92d30b694048d690e1c7354e0f4895bd5bf48bb74f661e817f6fd16bdcdd5f",
          "sha1": "e320e404557d9fc50f347df6a0881afc5c7cf22d",
          "md5": "65a6f4faa6d04631d880007197f8ed4e"
        }
      ]
    }
  ]
}
